############## Server port configuration ################   
server:
  port: 8888

############## Configuration for the jwt ################
jwt:
  security:
    key: ishanitech
  applicationName: ishanitech
  expirationDate: 864000000
  auth:
    header: Authorization
    schema: Bearer

############## Configuration for multipart surpport ###############
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
--- 
spring:
  profiles: dev
############## File Uploading Directory #################

database:
  username: root
  password: root

file:
  upload:
    directory: /ipasal/ipalika/
    
rest:
  protocol: http
  domain: localhost
  port: 8888
  resource-location: resource
---
spring:
  profiles: prod
  
database:
  username: root
  password: 24Pr1y@msh@  
  file:
  upload:
    directory: /home/ishani/ipalika/

rest:
  protocol: http
  domain: 103.233.58.121
  port: 8888
  resource-location: resource

