############## Configuration for multipart surpport ###############
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
############## File Uploading Directory #################
file:
  upload:
    directory: /Users/ishanitech/ipalika/

############## Server port configuration ################   
server:
  port: 8888


############## Configuration for the jwt ################
jwt:
  security:
    key: ishanitech
  applicationName: ishanitech
  expirationDate: 360000
  auth:
    header: Authorization
    schema: Bearer 
