package com.ishanitech.ipalika.model;

import lombok.Data;
import lombok.ToString;

@Data
@ToString
public class Answer {
	private long id;
	private long formId;
	private String entryDate;
	private String duration;
	private String filledId;
	private int addedBy;
	private int verifiedBy;
	private int modifiedBy;
	private String answer1;
	private String answer2;
	private String answer3;
	private String answer4;
	private String answer5;
	private String answer6;
	private String answer7;
	private String answer8;
	private String answer9;
	private String answer10;
	private String answer11;
	private String answer12;
	private String answer13;
	private String answer14;
	private String answer15;
	private String answer16;
	private String answer17;
	private String answer18;
	private String answer19;
	private String answer20;
	private String answer21;
	private String answer22;
	private String answer23;
	private String answer24;
	private String answer25;
	private String answer26;
	private String answer27;
	private String answer28;
	private String answer29;
	private String answer30;
	private String answer31;
	private String answer32;
	private String answer33;
	private String answer34;
	private String answer35;
	private String answer36;
	private String answer37;
	private String answer38;
	private String answer39;
	private String answer40;
	private String answer41;
	private String answer42;
	private String answer43;
	private String answer44;
	private String answer45;
	private String answer46;
	private String answer47;
	private String answer48;
	private String answer49;
	private String answer50;
	private String answer51;
	private String answer52;
	private String answer53;
	private String answer54;
	private String answer55;
	private String answer56;
	private String answer57;
	private String answer58;
	private String answer59;
	private String answer60;
}